development:
  adapter: postgresql
  database: rails_final_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: rails_final_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: rails_final_production
  pool: 5
  timeout: 5000